BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER,
	"username"	TEXT NOT NULL,
	"hash"	TEXT NOT NULL,
	"cash"	NUMERIC NOT NULL DEFAULT 10000.00,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "transactions" (
	"id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	"stock"	TEXT NOT NULL,
	"shares"	INTEGER NOT NULL,
	"price"	NUMERIC NOT NULL,
	"operation"	TEXT NOT NULL,
	"timestamp"	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY("user_id") REFERENCES "users"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE UNIQUE INDEX IF NOT EXISTS "username" ON "users" (
	"username"
);
COMMIT;
